// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypycxqlwbhfzkopfjmsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlweWN4cWx3YmhmemtvcGZqbXNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NjExMDAsImV4cCI6MjA2ODAzNzEwMH0.JHe2mldSPYnSue5AdoNSvUwbgZRLXR8yB6lE5D1nN5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});